### ISSUE TITLE
Mobile Hamburger menu opens over components

### ISSUE THREAD

**Issue by ChrisS561** [ChrisS561/author-books-website#22]
The Mobile hamburger menu opens over the components, instead of pushing them down. This can be confusing for users, as it can be difficult to see the content of the menu when it is open.

### Expected behavior:

When the hamburger menu is opened, it should push the components underneath down, so that the menu is visible and the user can interact with it.

**Comment by Sky-De** [comment]
@ChrisS561  please assign this to me
I'll fix this
thanks

**Comment by ChrisS561** [comment]
While I'm not entirely sure about how the UI would look with this feature, @Sky-De, feel free to get creative and share your innovative ideas!
