### ISSUE TITLE
Website Responsiveness Problem

### ISSUE THREAD

**Issue by ChrisS561** [ChrisS561/author-books-website#29]

**Comment by ChrisS561** [comment]
@Sky-De This is a great idea, look forward to seeing the results

**Comment by Sky-De** [comment]
@ChrisS561 hi again, if you still working on this project please assign this issue to me
I would like to take a look at it
Thanks

**Comment by ChrisS561** [comment]
@Sky-De Thanks for your message. I'm still working on this project, and I'm happy to assign this issue to you. I appreciate your help.
